### PR TITLE
GPLv3+ license added

### PR DESCRIPTION
**Pull request by comradekingu**
Needs approval from contributors.
If that includes me, I approve.

### CODE REVIEW

**Comment by jeremypw** [comment]
Closing as unreviewed after 2+ years

**Comment by comradekingu** [comment]
@jeremypw
A compelling reason to do something about it.
This is the promise made:
bilde

**Comment by jeremypw** [comment]
@comradekingu Maybe, but this repository has not been updated in four years so appears to be defunct.  @danirabbit is this repo still needed?

**Comment by danirabbit** [comment]
Yeah I can confirm we haven't published a syslinux theme package since 2019: 

https://code.launchpad.net/~elementary-os/+archive/ubuntu/stable/+packages?field.name_filter=syslinux&field.status_filter=published&field.series_filter=

https://code.launchpad.net/~elementary-os/+archive/ubuntu/daily/+packages?field.name_filter=syslinux&field.status_filter=published&field.series_filter=

so this repository can probably be archived

**Pull request closed without merging**
